[misc]

disable = [
    "bun",
    "bun_packages",
    "cargo",
    "clam_av_db",
    "containers",
    "gcloud",
    "gem",
    "github_cli_extensions",
    "go",
    "home_manager",
    "mamba",
    "nix",
    "nix_helper",
    "node",
    "poetry",
    "pnpm",
    "pyenv",
    "rye",
    "self_update",
    "shell",
    "uv",
    "vim",
    "yarn",
    "yazi",
]
